### PR TITLE
Amendment to Currency Act of 2016.md

### PR DESCRIPTION
**Pull request by Velonere**

### CODE REVIEW

**Comment by TRManderson** [comment]
This is illegal

**Comment by rslabbert** [comment]
While I am neutral to the proposed name changes, I think changing the currency to follow a decimal system would be beneficial.

But as @TRManderson stated, only the finance minister is allowed to change the currency act.

**Comment by TRManderson** [comment]
I too am definitely in favour of a decimal currency system, but this is illlegal.

**Comment by Guthers** [comment]
I am also in support of a decimal currently system

**Comment by Velonere** [comment]
As I do not believe specific positions have been assigned to ministers, there is no Financial Minister thus with this proposal, I am offering my candidacy for the position.

**Comment by TRManderson** [comment]
We're discussing allocation of ministries on #11

**Comment by TRManderson** [comment]
I think we're going to work out what the ministries are before we decide who has each though

**Comment by lsenjov** [comment]
Please note Constitution 1.1.2.b.a Only the financial minister may create pull requests affecting the Currency Act of 2016.

**Pull request closed without merging**
