### PR TITLE
Added rational guidelines to constitution.

### PR DESCRIPTION
**Pull request by rslabbert**
Added rational guidelines which would prevent laws which cannot be justified.

### CODE REVIEW

**Comment by TRManderson** [comment]
While I am strongly in favour of the suggested 1.1.2.f, I have concerns about 1.1.2.e

**Comment by rslabbert** [comment]
@TRManderson What are the concerns?

**Comment by TRManderson** [comment]
I think "logical argument" is too ambiguous, honestly.

**Comment by rslabbert** [comment]
I agree, but I think this could provide a framework for discussion.

**Comment by CameronAavik** [comment]
Can you give an example of what you would consider a logical argument and not a logical argument. I agree with tom that this is too vague

**Comment by ghost** [comment]
I agree with TRManderson. I think the players have demonstrated that they can keep nonsense out of the game by voting against my proposition.

**Comment by rslabbert** [comment]
I think for the purposes of this discussion a logical argument can be roughly defined as a series of true or false statements that build on each other to reach a conclusion.

It's also important to note that applying this absolutely can be detrimental, and thus might have to be open to probabilistic arguments.

But the reasoning that this is too vague makes sense, so I might pull the second amendment into a secondary pull request.

**Comment by lsenjov** [comment]
No votes, not ratified.

**Pull request closed without merging**
